# Generated by Django 4.2.21 on 2025-05-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("deleted", "Deleted"),
                    ("logged_in", "Logged In"),
                    ("logged_out", "Logged Out"),
                ],
                max_length=10,
            ),
        ),
        # migrations.AlterField(
        #     model_name="user",
        #     name="email",
        #     field=models.EmailField(db_index=True, max_length=254, unique=True),
        # ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
