# Generated by Django 4.2.21 on 2025-05-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_auditlog_action_alter_user_email_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="telephone",
            new_name="phone",
        ),
        migrations.AddField(
            model_name="auditlog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="success",
            field=models.BooleanField(default=True),
        ),
    ]
