# Generated by Django 5.2 on 2025-04-18 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_meter_credit_balance_alter_bill_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="technician",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "technician"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_complaints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="is_applied",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="meter",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("disconnected", "Disconnected"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TokenAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "meter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.meter"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="core.transaction",
                    ),
                ),
            ],
        ),
    ]
