# Generated by Django 4.2.21 on 2025-05-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_changelog_auditlog_alter_user_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="user_snapshot",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
