# Generated by Django 4.2.21 on 2025-05-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_telephone_user_phone_auditlog_metadata_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("deleted", "Deleted"),
                    ("logged_in", "Logged In"),
                    ("logged_out", "Logged Out"),
                    ("password_reset", "Password Reset"),
                    ("password_changed", "Password Changed"),
                ],
                max_length=50,
            ),
        ),

    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
    ]
