# Generated by Django 4.2.21 on 2025-05-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_auditlog_action_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="meter",
            name="description",
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name="meter",
            name="meter_type",
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("updated", "Updated"),
                    ("deleted", "Deleted"),
                    ("logged_in", "Logged In"),
                    ("logged_out", "Logged Out"),
                    ("password_reset", "Password Reset"),
                    ("password_changed", "Password Changed"),
                ],
                max_length=50,
            ),
        ),
    ]
