# Generated by Django 4.2.21 on 2025-05-27 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auditlog_user_snapshot"),
        ("core", "0005_meter_description_meter_meter_type_and_more"),
    ]

    operations = []
