# Generated by Django 4.2.21 on 2025-05-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='meter_type',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
