# Generated by Django 4.2.21 on 2025-05-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_merge_20250527_0005"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("applied", "Applied"), ("expired", "Expired")],
                default="pending",
                max_length=20,
            ),
        ),

    ]
